[package]
name = "webservice_emote_mattermost"
version = "0.1.0"
authors = ["sle-guil"]

[dependencies]
rocket = "0.3.5"
rocket_codegen = "0.3.5"
rocket_contrib = {version = "0.3", default-features = false, features = ["json"]}

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"